sudo: required
services:
  - docker

script:
  - docker build -t alejux/node-docker .
  - docker images alejux/node-docker

before_deploy:
  - docker login -u alejuxcr -p Ucanthackthis110101

deploy:
  provider: script
  script: docker push alejux/node-docker
  on:
    branch: master