sudo: required
services:
  - docker

script:
  - docker build -t alejuxcr/node-docker .
  - docker images alejuxcr/node-docker

before_deploy:
  - docker login -u alejuxcr -p Ucanthackthis110101

deploy:
  provider: script
  script: docker push alejuxcr/node-docker
  on:
    branch: master